---
# tasks file for faba.docker
- name: "Check for docker-py module"
  shell: "pip list | grep 'docker-py ' || true"
  register: docker_py
  ignore_errors: true
  changed_when: false
  tags:
    - docker

- name: "Check for docker module"
  shell: "pip3 list | grep 'docker ' || true"
  register: docker_python3
  ignore_errors: true
  changed_when: false
  tags:
    - docker

- name: "Check if Python-pip is installed"
  package_facts:
  tags:
    - docker

- name: "Remove docker-py module"
  pip:
    name: docker-py
    #version: 1.9.0
    state: absent
    executable: pip
  when: "'python-pip' in ansible_facts.packages"
  tags:
    - docker

- name: "Remove docker module"
  pip:
    name: docker
    #version: 1.9.0
    state: absent
    executable: pip3
  when: docker_py.stdout | length > 0 and docker_python3.stdout | length > 0
  tags:
    - docker
    
    
- name: "Remove docker from snap"
  snap:
    name: docker
    state: absent
  tags:
    - docker
  ignore_errors: yes

- name: "Download Docker"
  get_url:
    url: "https://get.docker.com/"
    dest: "/tmp/docker.sh"
  #when: ansible_lsb.id == "Ubuntu"
  tags:
    - docker

- name: "Install Docker"
  shell: "sh /tmp/docker.sh"
  args:
    creates: "/usr/bin/docker"
  #when: ansible_lsb.id == "Ubuntu"
  tags:
    - docker

- name: "Install docker module"
  pip:
    name: docker
    state: present
    executable: pip3
  tags:
    - docker

- name: "Install SSL_Hostname_match"
  package:
    name: "python-backports.ssl-match-hostname"
    state: present
  tags:
    - docker

- name: "Ensure Docker Service is running"
  service:
    name: "docker"
    state: "started"
  tags:
    - docker
